myblog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myblog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('zhidaow.urls', namespace='zhidaow')),
)

zhidaow/urls.py
from django.conf.urls import patterns, url

from zhidaow import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^column/(?P<pk>\d+)/$', views.column, name='column'),
	url(r'^post/(?P<pk>\d+)$', views.post, name='post'),
	url(r'^tag/(?P<pk>\d+)/$', views.tag, name='tag'),
	url(r'^author/(?P<pk>\d+)/$', views.author, name='author'),
)

zhidaow/models.py
#coding=utf-8
from django.db import models
from django.utils import timezone

# Create your models here.
class Author(models.Model):
	name = models.CharField(max_length=200)
	description = models.CharField(max_length=1000)

	class Meta:
		verbose_name = '作者'
		verbose_name_plural = '作者'

	def __unicode__(self):
		return u'%s' % self.name


class Column(models.Model):
	name = models.CharField(max_length=200)
	description = models.CharField(max_length=1000)

	class Meta:
		verbose_name = '栏目'
		verbose_name_plural = '栏目'

	def __unicode__(self):
		return u'%s' % self.name


class Tag(models.Model):
	name = models.CharField(max_length=200)
	description = models.CharField(max_length=1000)

	class Meta:
		verbose_name = '标签'
		verbose_name_plural = '标签'

	def __unicode__(self):
		return u'%s' % self.name

class Post(models.Model):
	title = models.CharField(max_length=200)
	description = models.CharField(max_length=1000)
	date = models.DateTimeField(default=timezone.now())
	author = models.ForeignKey(Author)
	column = models.ForeignKey(Column)
	tag = models.ManyToManyField(Tag)
	status = models.BooleanField(default=True)
	visits = models.IntegerField(default=0)
	content = models.TextField(max_length=3000)

	class Meta:
		verbose_name = '文章'
		verbose_name_plural = '文章'

	def __unicode__(self):
		return '%s' % self.title

zhidaow/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.http import HttpResponse
from zhidaow.models import Post, Author, Column, Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
pagenum = 2

def index(request):
	post_list = get_list_or_404(Post.objects.order_by('-date'), status=True)
	paginator = Paginator(post_list, pagenum)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)

	return render(request, 'zhidaow/index.html', {'posts': posts})

def post(request, pk):
	post = get_object_or_404(Post, pk=pk)
	post.visits += 1
	post.save()
	return render(request, 'zhidaow/post.html', {'post': post})

def author(request, pk):
	author = get_object_or_404(Author, pk=pk)
	posts_list = get_list_or_404(Post.objects.order_by('-date'), status=True, author=author)
	paginator = Paginator(posts_list, pagenum)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)
	return render(request, 'zhidaow/author_list.html', {'author': author, 'posts': posts})

def tag(request, pk):
	tag = get_object_or_404(Tag, pk=pk)
	posts_list = get_list_or_404(Post.objects.order_by('-date'), status=True, tag=tag)
	paginator = Paginator(posts_list, pagenum)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)
	return render(request, 'zhidaow/tag_list.html', {'tag': tag, 'posts': posts})

def column(request, pk):
	column = get_object_or_404(Column, pk=pk)
	posts_list = get_list_or_404(Post.objects.order_by('-date'), status=True, column=column)
	paginator = Paginator(posts_list, pagenum)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)
	return render(request, 'zhidaow/column_list.html', {'column': column, 'posts': posts})

zhidaow/templates/zhidaow/author_list.html
{% extends 'zhidaow/base.html' %}

{% block title %}{{ author.name }}'s articles - 张亚楠的个人博客{% endblock %}
{% block description %}<meta name="description" content="张亚楠的个人博客，专门记录个人杂事。" />{% endblock %}

{% block content %}


        <div class="container" id="posts">
	<div><h1>Articles writed by {{ author.name }}</h1></div>
        {% include 'zhidaow/posts_list.html' %}
        </div>

{% endblock %}

zhidaow/templates/zhidaow/base.html
{% load markdown_deux_tags %}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="cn-zh">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>{% block title %}张亚楠的个人博客{% endblock %}</title>
	{% block description %}{% endblock %}
    <link href="http://www.zhidaow.com/service/static/css/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!--[if IE 7]>
    <link href="http://www.zhidaow.com/css/font-awesome/css/font-awesome-ie7.min.css" rel="stylesheet" type="text/css" />
    <![endif]-->
    <link rel="stylesheet" href="http://www.zhidaow.com/service/static/css/default-template-v3.css?version={{ resource_version }}">
    <link rel="stylesheet" href="http://www.zhidaow.com/service/static/css/basic.css?version={{ resource_version }}">

    {% block head %}
    {% endblock %}

</head>
<body>


<div id="header" style="background: #403D39">

    <ul id="nav">
        <li>
            <a href="/">Home</a>
        </li>
        <li>
            <a href="#">Archive</a>
        </li>
        <li>
            <a href="#">Categories</a>
        </li>
        <li>
            <a href="#">Tags</a>
        </li>
        <li>
            <a href="#">Photo</a>
        </li>
        <li>
            <a href="#">Links</a>
        </li>
        <li>
            <a href="#">About</a>
        </li>
    </ul>
</div>

{% block content %}
{% endblock %}




<div id="footer">
    <div class="powered_by">
        <a target='_blank' href="http://www.farbox.com">Proudly Powered By FarBox.com!</a>
        <span>©2012-2015 Z.R.E.Y Inc.</span>
    </div>
</div>





</body>
</html>

zhidaow/templates/zhidaow/column_list.html
{% extends 'zhidaow/base.html' %}

{% block title %}About {{ column.name}}'s articles - 张亚楠的个人博客{% endblock %}
{% block description %}<meta name="description" content="张亚楠的个人博客，专门记录个人杂事。" />{% endblock %}

{% block content %}


        <div class="container" id="posts">
	<div><h1>Articles about {{ column.name }} </h1></div>
        {% include 'zhidaow/posts_list.html' %}
        </div>

{% endblock %}

zhidaow/templates/zhidaow/index.html
{% extends 'zhidaow/base.html' %}

{% block title %}张亚楠的个人博客 - 山不在高，有仙则灵{% endblock %}
{% block description %}<meta name="description" content="张亚楠的个人博客，专门记录个人杂事。" />{% endblock %}

{% block content %}


        <div class="container" id="posts">
        {% include 'zhidaow/posts_list.html' %}
        </div>

{% endblock %}

zhidaow/templates/zhidaow/post.html
{% extends 'zhidaow/base.html' %}
{% load markdown_deux_tags %}
{% block title %}{{ post.title }} - 张亚楠 ' BLOG{% endblock %}


{% block content %}
<div class="container" id="posts">
    <div class="post detail_post">
        <h1 class="title"><a href="{% url 'zhidaow:post' post.id %}">{{ post.title }}</a></h1>

        <div class="post_body">
            {{ post.content|markdown:"STYLE" }}
        </div>

        <div class="info">
			<span class="author" style="float:right;">
				作者：<a href="{% url 'zhidaow:author' post.author.id%}">{{ post.author.name }}</a>
			</span>
		    <span class="date" title="发布日期">
                <i class="icon-clock"></i>
                {{ post.date|date:"Y-n-j G:i" }}
            </span>
		    <span class="visitors" title="访问量">
                <i class="icon-user"></i>
                {{ post.visits}}
            </span>
			<span class="tags">
				<i class="icon-tags"></i>
				<a href="{% url 'zhidaow:column' post.column.id%}">{{ post.column.name }}</a>
			</span>

            {% if post.tag %}
	        <span class="tags">
	            <i class="icon-tags"></i>
				{% for tag in post.tag.all %}
				<a href="{% url 'zhidaow:tag' tag.id %}">{{tag.name}}</a>
				{% endfor %}
            </span>
            {% endif %}
	    </div>
    </div>


</div>
{% endblock %}

zhidaow/templates/zhidaow/posts_list.html
{% load markdown_deux_tags %}
{% for post in posts %}
    <div class="post">
        <h2 class="title">
            <a href="{% url 'zhidaow:post' post.id %}">{{ post.title }}</a>
        </h2>

        <div class="post_body">
            {{ post.content|markdown|truncatewords:"30"}}
        </div>

     <div class="info">
		    <span class="date" title="发布日期">
                <i class="icon-clock"></i>
                {{ post.date|date:"Y-n-j G:i" }}
            </span>
		    <span class="visitors" title="访问量">
                <i  class="icon-user"></i>
                {{ post.visits}}
            </span>
			<span class="tags">
				<i class="icon-tags"></i>
				<a href="{% url 'zhidaow:column' post.column.id %}">{{ post.column.name}}</a>
			</span>

            {% if post.tag %}
	        <span class="tags">
	            <i class="icon-tags"></i>
				{% for tag in post.tag.all %}
	             <a href="{% url 'zhidaow:tag' tag.id %}">{{ tag.name }}</a>
				 {% endfor %}
            </span>
            {% endif %}


            <div class="read_more">
                <a href="{% url 'zhidaow:post' post.id %}">>阅读全文</a>
            </div>
	    </div>


    </div>
{% endfor %}

<div class="pager">
		{% if posts.has_previous %}
			<a class="round pre" href="?page={{ posts.previous_page_number }}">上一页</a>
		{% endif %}

		{% if posts.has_next %}
			<a class="round next" href="?page={{ posts.next_page_number }}">下一页</a>
		{% endif %}
</div>

zhidaow/templates/zhidaow/tag_list.html
{% extends 'zhidaow/base.html' %}

{% block title %}About {{tag.name}}'s articles - 张亚楠的个人博客{% endblock %}
{% block description %}<meta name="description" content="张亚楠的个人博客，专门记录个人杂事。" />{% endblock %}

{% block content %}


        <div class="container" id="posts">
	<div><h1>Articles about {{ tag.name }} </h1></div>
        {% include 'zhidaow/posts_list.html' %}
        </div>

{% endblock %}